# Generated by Django 2.2.5 on 2019-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20190929_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='movies',
            name='gener',
            field=models.TextField(max_length=80),
        ),
    ]
